// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrM5ZYQb4gNH2NF2XBtpZkAS--8zKoJvA',
    appId: '1:971379888870:web:e05da49dc0a72afeb5a127',
    messagingSenderId: '971379888870',
    projectId: 'newirene-b23bb',
    authDomain: 'newirene-b23bb.firebaseapp.com',
    storageBucket: 'newirene-b23bb.firebasestorage.app',
    measurementId: 'G-CZD6TTPBEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaXbt-PzkHxBikHqycN6mhv8vpDZfsKk4',
    appId: '1:971379888870:android:c48209f1b490e332b5a127',
    messagingSenderId: '971379888870',
    projectId: 'newirene-b23bb',
    storageBucket: 'newirene-b23bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-Xn46nNb9_ndyww9P8NnWJlS1Bw5ylOU',
    appId: '1:971379888870:ios:9ed7ac1415697586b5a127',
    messagingSenderId: '971379888870',
    projectId: 'newirene-b23bb',
    storageBucket: 'newirene-b23bb.firebasestorage.app',
    iosBundleId: 'com.example.ireneTraining',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-Xn46nNb9_ndyww9P8NnWJlS1Bw5ylOU',
    appId: '1:971379888870:ios:9ed7ac1415697586b5a127',
    messagingSenderId: '971379888870',
    projectId: 'newirene-b23bb',
    storageBucket: 'newirene-b23bb.firebasestorage.app',
    iosBundleId: 'com.example.ireneTraining',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrM5ZYQb4gNH2NF2XBtpZkAS--8zKoJvA',
    appId: '1:971379888870:web:cef330a648963087b5a127',
    messagingSenderId: '971379888870',
    projectId: 'newirene-b23bb',
    authDomain: 'newirene-b23bb.firebaseapp.com',
    storageBucket: 'newirene-b23bb.firebasestorage.app',
    measurementId: 'G-V1TPDHX0K2',
  );

}