-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgB19JqNpiS4mfEgl5
Wrs4GCz8GnSosjbzqjl9qmOGpN2gCgYIKoZIzj0DAQehRANCAASCYceHF7NglBQH
tmVgKlWdKJIhQJtqLLduIoU8IWzxqfci63ImA4YIqXKGb0PXkb3ewIt8g2Ch7pwX
2oVfu+dH
-----END PRIVATE KEY-----