-- ============================================================
-- TaskType_Report_Subject: ผูก taskType (string) กับ Report_Subject
-- กำหนดว่า task ประเภทไหนต้องประเมิน subject อะไรบ้าง
-- เช่น taskType = 'อาหาร' → ประเมิน Subject #2 (การรับประทานอาหาร)
-- ============================================================

CREATE TABLE IF NOT EXISTS "public"."TaskType_Report_Subject" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamptz DEFAULT now() NOT NULL,

  -- taskType ตรงกับ A_Tasks.taskType / C_Tasks.taskType
  "task_type" text NOT NULL,

  -- subject ที่ต้องประเมิน
  "subject_id" bigint NOT NULL REFERENCES "public"."Report_Subject"("id") ON UPDATE CASCADE ON DELETE CASCADE,

  -- แต่ละ nursing home อาจกำหนด mapping ต่างกันได้
  "nursinghome_id" bigint NOT NULL,

  -- ป้องกัน duplicate: 1 taskType + 1 subject + 1 nursinghome = 1 row
  UNIQUE ("task_type", "subject_id", "nursinghome_id")
);

COMMENT ON TABLE "public"."TaskType_Report_Subject" IS
  'ผูก taskType กับ Report_Subject — กำหนดว่า task ประเภทไหนต้องประเมินอะไรตอน complete';

-- ============================================================
-- RLS
-- ============================================================

ALTER TABLE "public"."TaskType_Report_Subject" ENABLE ROW LEVEL SECURITY;

-- Staff ใน nursing home เดียวกันอ่านได้
CREATE POLICY "active_read" ON "public"."TaskType_Report_Subject"
  FOR SELECT TO authenticated
  USING (
    "nursinghome_id" = public.get_current_user_nursinghome_id()
    AND public.is_active_employee()
  );

-- หัวหน้าเวร+ (level >= 30) จัดการได้
-- user_info.role_id → user_system_roles.level
CREATE POLICY "hq_manage" ON "public"."TaskType_Report_Subject"
  FOR ALL TO authenticated
  USING (
    "nursinghome_id" = public.get_current_user_nursinghome_id()
    AND public.is_active_employee()
    AND (
      SELECT usr.level FROM public.user_info ui
      JOIN public.user_system_roles usr ON usr.id = ui.role_id
      WHERE ui.id = auth.uid()
    ) >= 30
  )
  WITH CHECK (
    "nursinghome_id" = public.get_current_user_nursinghome_id()
    AND public.is_active_employee()
    AND (
      SELECT usr.level FROM public.user_info ui
      JOIN public.user_system_roles usr ON usr.id = ui.role_id
      WHERE ui.id = auth.uid()
    ) >= 30
  );

-- Service role bypass
CREATE POLICY "service_role_all" ON "public"."TaskType_Report_Subject"
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- ============================================================
-- Grants & Indexes
-- ============================================================

GRANT ALL ON TABLE "public"."TaskType_Report_Subject" TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE "public"."TaskType_Report_Subject_id_seq" TO anon, authenticated, service_role;

CREATE INDEX "idx_tasktype_report_subject_type" ON "public"."TaskType_Report_Subject" ("task_type", "nursinghome_id");
CREATE INDEX "idx_tasktype_report_subject_subject" ON "public"."TaskType_Report_Subject" ("subject_id");

-- ============================================================
-- Seed: Default mapping สำหรับ nursinghome_id = 1
-- (เพิ่ม nursinghome อื่นได้ทีหลังผ่าน admin)
-- ============================================================

INSERT INTO "public"."TaskType_Report_Subject" ("task_type", "subject_id", "nursinghome_id") VALUES
  -- อาหาร → #2 การรับประทานอาหาร (ทานได้กี่ %)
  ('อาหาร', 2, 1),

  -- ดูแลร่างกาย → #4 การเคลื่อนไหว + #27 ความร่วมมือ
  ('ดูแลร่างกาย', 4, 1),
  ('ดูแลร่างกาย', 27, 1),

  -- พลิกตะแคงตัว → #28 อาการปวด
  ('พลิกตะแคงตัว', 28, 1),

  -- กายภาพ → #4 การเคลื่อนไหว + #27 ความร่วมมือ
  ('กายภาพ', 4, 1),
  ('กายภาพ', 27, 1),

  -- กิจกรรม → #3 อารมณ์ + #22 กิจกรรมประจำวัน
  ('กิจกรรม', 3, 1),
  ('กิจกรรม', 22, 1),

  -- ยานอกมื้อหลัก → #27 ความร่วมมือ
  ('ยานอกมื้อหลัก', 27, 1),

  -- หัตถการ → #28 อาการปวด + #27 ความร่วมมือ
  ('หัตถการ', 28, 1),
  ('หัตถการ', 27, 1),

  -- ขับถ่าย → #29 ปัสสาวะ
  ('ขับถ่าย', 29, 1)

ON CONFLICT DO NOTHING;
